import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav>
          <div className='navbar bg-base-100 shadow-sm'>
            {/* <a className='btn btn-ghost text-xl'>daisyUI</a> */}
            <Link href={`/`} className='btn btn-ghost text-xl'>
              Home
            </Link>
            <br />
            <Link href={`/dashboard`} className='btn btn-ghost text-xl'>
              Dashboard
            </Link>
            <br />
            <Link href={`/sign-up`} className='btn btn-ghost text-xl'>
              SignUp
            </Link>
            <br />
            <Link href={`/sign-in`} className='btn btn-ghost text-xl'>
              SignIn
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
